import type { Metadata } from "next";
import { Jersey_10 } from "next/font/google";
import "./globals.css";
// import { ApolloWrapper } from "./ApolloWrapper";

const jersey = Jersey_10({
  weight: "400",
  variable: "--font-jersey-10",
  style: "normal",
  preload: true,
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Pokemon Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${jersey.variable}`}
      > 
      {/* <ApolloWrapper> */}
          {children}
        {/* </ApolloWrapper> */}
      </body>

    </html>
  );
}
