import type { Metadata } from "next";
import { Jersey_10 } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";

const jersey = Jersey_10({
  weight: "400",
  variable: "--font-jersey-10",
  style: "normal",
  preload: true,
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Jersey+20&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`antialiased ${jersey.variable}`}
      > <ApolloWrapper>
          {children}
        </ApolloWrapper>
      </body>

    </html>
  );
}
